ALTER USER 'alex'@'%' IDENTIFIED WITH mysql_native_password BY 'mysql';
FLUSH PRIVILEGES;

CREATE TABLE Department_Employee (
    DEPARTMENT VARCHAR(100),
    DEPARTMENT_DIVISION VARCHAR(100),
    POSITION_TITLE VARCHAR(100),
    HIRE_DATE DATE,
    SALARY DECIMAL
);

CREATE TABLE Department_Employee_Salary (
    DEPARMENT VARCHAR(100) NOT NULL,
    TOTAL_SALARY INT(4),
    PRIMARY KEY (department)
)
